### ISSUE TITLE
Peer review for Kate Roth by Susan Collins

### ISSUE THREAD

**Issue by susancollins** [2020-bgmp/demultiplexing-kate-roth#1]
line 48:
What datatype are the values of the index dictionary stored in?

line 117:
Not seeing where you store the reverse complemented indexes in a dictionary

Otherwise, looking great! Good work!

**Comment by kate-roth** [comment]
line 48:
I was thinking maybe tuples if they take up less space, but otherwise lists

line 117:
index2 sequences are reversed complemented, so the reverse complement of the index2 sequence should be the same as indexes in the dictionary
