### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by megan-criss** [2020-bgmp/demultiplexing-kate-roth#2]
[Peer Review kate.pdf](https://github.com/2020-bgmp/demultiplexing-kate-roth/files/5013231/Peer.Review.kate.pdf)

**Comment by megan-criss** [comment]
Hi Kate! Here is your peer review, let me know if you have any questions or if the link doesn't work :)

**Comment by kate-roth** [comment]
Hi Megan! Thank you for your feedback! I'm planning on concatenating the index1 and index2 sequences to the header lines of the R1 and R4 records with a "-" in between. The dictionary will already contain the counts for the matched (keys that are (index,index) and index-hopped, and there's the global variable for unknown/low quality but it could be useful to have a global general count for index-hopped. The global variable for unknown/low quality counts will just generally count the number of pairs that are unknown or low quality.
