### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by srhintonPL** [2020-bgmp/demultiplexing-kate-roth#3]
Yooooo Kate!

All of the above looks pretty darn good to me. Knowing that you are a far better programmer than me (I just started a whole 4 weeks ago lol) I am finding it hard to to come up with anything helpful. However I will do my best to come up with something constructive lol. 

okay so the only thing I can think of is maybe making a unit test for your quality score cut off since I do not think I saw one in your prose.  Hopefully this is just a helpful reminder in case you forget to check it.

Everything else looks fantastic!

**Comment by kate-roth** [comment]
Noted! Thanks for the feedback Sam! :)

**Comment by kate-roth** [comment]
Noted! Thanks for the feedback Sam! :)
